import { google } from '@ai-sdk/google';
import { generateText } from 'ai';
import { NextResponse } from 'next/server';

let chatHistory = [];

/**
 * Updates the chat history with a new message and maintains a maximum of 10 messages.
 *
 * @param {string} role - The role of the message sender (e.g., "user" or "bot").
 * @param {string} content - The content of the message to be added to chat history.
 */
async function updateChatHistory(role, content) {
    chatHistory.push({ role, content });
    if (chatHistory.length > 20) {
        chatHistory = chatHistory.slice(chatHistory.length - 10); // Keep last 10 messages
    }
}

/**
 * Handles incoming POST requests to the /api/gemini endpoint.
 *
 * Request body must contain a JSON object with the following properties:
 * - `prompt`: The user's input to be sent to the AI model.
 * - `imgPrompt`: The URL of the image to be sent to the AI model, if any.
 *
 * The endpoint returns a JSON response with the following properties:
 * - `response`: The text generated by the AI model.
 * - `error`: An error message if there was an error generating text.
 * @param {NextApiRequest} req
 * @returns {Promise<NextApiResponse>}
 */

/**
 * Handles incoming POST requests to the /api/gemini endpoint.
 *
 * Request body must contain a JSON object with the following properties:
 * - `prompt`: The user's input to be sent to the AI model.
 * - `imgPrompt`: The URL of the image to be sent to the AI model, if any.
 *
 * The endpoint returns a JSON response with the following properties:
 * - `response`: The text generated by the AI model.
 * - `error`: An error message if there was an error generating text.
 *
 * @param {NextApiRequest} req
 * @returns {Promise<NextApiResponse>}
 */
export async function POST(req) {
    const { prompt, imgPrompt } = await req.json();

    const content = [
        {
            type: 'text',
            text: `
                You are Rosta, a helpful and friendly AI assistant bot created for **Aosta Hub**, a platform built by **Karim El Assali**. Aosta Hub is a community-based platform for people living in **Aosta city**, where users can meet new people, chat, and form friendships. Your purpose is to assist users, answer their questions, and help them interact within the community.
    
                You should always respond concisely, in the same language as the user’s request, and make sure to maintain a friendly, helpful tone. Always refer to yourself as **Rosta** and Aosta Hub as **Aosta Hub**.
    
                History: ${JSON.stringify(chatHistory)}
                Request: ${prompt}
            `,
        },
    ];
    
    if (imgPrompt) {
        content.push({
            type: 'file',
            data: `https://giyrlrcehqsypefjoayv.supabase.co/storage/v1/object/public/aiFiles/${imgPrompt}`,
            mimeType: 'image/*',
        });
    }

    const response = await generateText({
        model: google('gemini-1.5-flash'),
        messages: [{ role: 'user', content }],
    });

    if (response) {
        await Promise.all([
            updateChatHistory('user', prompt),
            updateChatHistory('assistant', response.text)
        ]);
    }

    return NextResponse.json({ response: response.text })
}